# Generated by Django 4.2.2 on 2023-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_url',
            field=models.CharField(max_length=150),
        ),
    ]
