# Generated by Django 4.2.2 on 2023-07-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work_work_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articles_subname',
            field=models.CharField(default=2023, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='articles_year',
            field=models.IntegerField(default=2023, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='articles_name',
            field=models.CharField(max_length=80),
        ),
    ]
