# Generated by Django 4.2.2 on 2023-07-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_country_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
    ]
